name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Java 12
        uses: actions/setup-java@v1
        with:
          java-version: "12"

      - name: Build the application
        run: mvn clean install -Dmaven.test.skip=true

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mysterious-mesa-72833" #Must be unique in Heroku
          heroku_email: "dre086@gmail.com"
          usedocker: true

      - name: Get the Heroku app URL dynamically
        run: |
          app_url=$(heroku apps:info --app mysterious-mesa-72833 | grep "Web URL" | awk '{print $3}')
          echo "Heroku app URL is: $app_url"
          echo "HEROKU_APP_URL=$app_url" >> $GITHUB_ENV

      - name: Run API tests against Heroku
        run: mvn test -P=e2e -Dheroku.app.url=${{ env.HEROKU_APP_URL }}
